export interface ServiceCategory {
  id: string;
  number: string;
  title: string;
  tagline: string;
  headline: string;
  description: string;
  iconName: string;
  skills: string[];
}

export const SERVICE_CATALOG: ServiceCategory[] = [
  {
    id: 'strategy-consulting',
    number: '01',
    title: 'Strategy & Consulting',
    tagline: 'Ideas → Direction',
    headline: 'Ideas to Strategic Direction',
    description:
      'We turn complex business challenges into clear product strategies, roadmaps and technical directions.',
    iconName: 'Compass',
    skills: [
      'Digital Strategy',
      'Product Strategy',
      'Technology Consulting',
      'Digital Transformation',
      'Business Process Analysis',
      'Product Discovery',
      'MVP Strategy',
      'Go-To-Market Strategy',
      'Technical Feasibility Analysis',
      'Product Roadmapping',
      'Digital Transformation Consulting',
      'Technology Stack Consulting',
      'Business Model Strategy',
      'Digital Product Consulting',
      'Product-Market Fit Strategy',
    ],
  },
  {
    id: 'web-development',
    number: '02',
    title: 'Web Development',
    tagline: 'Experiences That Perform',
    headline: 'High-Performance Web Platforms',
    description:
      'High-performance websites and web applications engineered around users, business objectives and measurable outcomes.',
    iconName: 'Globe',
    skills: [
      'Corporate Website Development',
      'Business Website Development',
      'Startup Website Development',
      'Landing Page Development',
      'Marketing Website Development',
      'Custom Website Development',
      'Custom Web Application Development',
      'Progressive Web App Development',
      'Web Portal Development',
      'Membership Website Development',
      'Directory Platform Development',
      'Marketplace Development',
      'Booking Platform Development',
      'Customer Portal Development',
      'Client Portal Development',
      'Internal Web Application Development',
      'Interactive Website Development',
      'High-Performance Website Development',
      'Headless Website Development',
      'Jamstack Development',
      'Next.js Development',
      'React Development',
      'TypeScript Development',
      'Frontend Development',
      'Full-Stack Web Development',
    ],
  },
  {
    id: 'saas-digital-products',
    number: '03',
    title: 'SaaS & Digital Products',
    tagline: 'Products That Scale',
    headline: 'Scalable Software Platforms',
    description:
      'From MVP to mature platform, we design and engineer SaaS products built for real users and real growth.',
    iconName: 'Layers',
    skills: [
      'SaaS Product Development',
      'SaaS MVP Development',
      'Multi-Tenant SaaS Development',
      'B2B SaaS Development',
      'B2C SaaS Development',
      'SaaS Dashboard Development',
      'SaaS Subscription Systems',
      'SaaS Billing Systems',
      'SaaS Authentication Systems',
      'SaaS User Management',
      'SaaS Admin Panels',
      'SaaS API Development',
      'SaaS Architecture',
      'SaaS Migration',
      'SaaS Performance Optimization',
      'SaaS Feature Development',
      'SaaS Product Redesign',
      'SaaS UI/UX Development',
      'SaaS Analytics Integration',
      'SaaS Maintenance & Scaling',
    ],
  },
  {
    id: 'mobile-development',
    number: '04',
    title: 'Mobile App Development',
    tagline: 'Products Beyond the Screen',
    headline: 'Native & Cross-Platform Mobile',
    description:
      'iOS, Android and cross-platform applications designed to deliver seamless experiences wherever your users are.',
    iconName: 'Smartphone',
    skills: [
      'iOS App Development',
      'Android App Development',
      'Cross-Platform App Development',
      'React Native Development',
      'Flutter Development',
      'Mobile MVP Development',
      'Consumer Mobile Apps',
      'Business Mobile Apps',
      'FinTech Apps',
      'Healthcare Apps',
      'Education Apps',
      'Marketplace Apps',
      'Booking Apps',
      'Social Apps',
      'On-Demand Apps',
      'Subscription Apps',
      'Mobile Commerce Apps',
      'Mobile Dashboard Development',
      'Mobile API Integration',
      'Mobile App Maintenance',
    ],
  },
  {
    id: 'ui-ux-design',
    number: '05',
    title: 'UI/UX & Product Design',
    tagline: 'Design That Reduces Friction',
    headline: 'Intuitive Experience Architecture',
    description:
      'We transform complex functionality into intuitive digital experiences that people understand and enjoy using.',
    iconName: 'Layout',
    skills: [
      'UI Design',
      'UX Design',
      'UX Research',
      'Product Design',
      'Digital Product Design',
      'SaaS UI Design',
      'Mobile UI Design',
      'Website UI Design',
      'Dashboard Design',
      'Design Systems',
      'Wireframing',
      'Interactive Prototyping',
      'User Journey Mapping',
      'Information Architecture',
      'Interaction Design',
      'Conversion-Focused UX',
      'UX Audit',
      'UI Audit',
      'Product Usability Testing',
      'Design System Development',
      'Responsive Interface Design',
      'Design-to-Development Handoff',
    ],
  },
  {
    id: 'branding-creative',
    number: '06',
    title: 'Branding & Creative',
    tagline: 'Identity With Intent',
    headline: 'Distinctive Digital Presence',
    description:
      'Strategic identities designed to give products and companies a distinctive presence in an increasingly crowded digital world.',
    iconName: 'Palette',
    skills: [
      'Brand Strategy',
      'Brand Identity',
      'Logo Design',
      'Visual Identity',
      'Brand Guidelines',
      'Typography Systems',
      'Color Systems',
      'Social Media Brand Kits',
      'Presentation Design',
      'Product Branding',
      'Corporate Branding',
      'Startup Branding',
      'Rebranding',
      'Brand Positioning',
      'Brand Voice & Messaging',
      'Creative Direction',
      'Digital Brand Experience',
      'Marketing Creative Design',
    ],
  },
  {
    id: 'ai-development',
    number: '07',
    title: 'AI Development',
    tagline: 'Intelligence in Action',
    headline: 'Practical AI & Autonomous Systems',
    description:
      "We integrate AI into products and operations where it creates genuine leverage — not simply because it's trending.",
    iconName: 'Bot',
    skills: [
      'AI Product Development',
      'AI SaaS Development',
      'AI Chatbot Development',
      'AI Customer Support Systems',
      'AI Knowledge Bases',
      'AI Search',
      'AI Recommendation Systems',
      'AI Document Processing',
      'AI Content Systems',
      'AI Data Analysis',
      'AI Workflow Automation',
      'LLM Integration',
      'AI API Integration',
      'RAG Systems',
      'AI Agent Development',
      'AI Assistants',
      'AI Copilots',
      'AI Lead Qualification',
      'AI Personalization',
      'AI Voice Applications',
      'AI Image Applications',
      'AI Document Intelligence',
      'AI Internal Tools',
      'AI-Powered Dashboards',
      'Custom AI Solutions',
    ],
  },
  {
    id: 'business-automation',
    number: '08',
    title: 'Business Automation',
    tagline: 'Less Manual. More Momentum.',
    headline: 'Connected Workflow Orchestration',
    description:
      'Intelligent workflows that connect tools, people and systems so businesses can spend less time on repetitive work.',
    iconName: 'Zap',
    skills: [
      'Business Automation',
      'Workflow Automation',
      'CRM Automation',
      'Lead Automation',
      'Email Automation',
      'WhatsApp Automation',
      'Customer Support Automation',
      'Sales Automation',
      'Marketing Automation',
      'Internal Operations Automation',
      'Invoice Automation',
      'Reporting Automation',
      'Notification Automation',
      'API Automation',
      'Data Automation',
      'Document Automation',
      'Approval Workflow Automation',
      'Employee Workflow Automation',
      'No-Code Automation',
      'Low-Code Automation',
      'AI Automation',
      'Multi-System Automation',
    ],
  },
  {
    id: 'backend-cloud',
    number: '09',
    title: 'Backend, API & Cloud',
    tagline: 'Foundations for Scale',
    headline: 'Resilient Infrastructure & APIs',
    description:
      'Secure, reliable infrastructure and backend systems engineered to support demanding digital products.',
    iconName: 'Server',
    skills: [
      'Backend Development',
      'Custom API Development',
      'REST API Development',
      'GraphQL API Development',
      'Database Architecture',
      'PostgreSQL Development',
      'MongoDB Development',
      'MySQL Development',
      'Authentication Systems',
      'Authorization Systems',
      'User Management Systems',
      'Cloud Architecture',
      'Serverless Development',
      'Cloud Migration',
      'DevOps',
      'CI/CD Implementation',
      'Infrastructure as Code',
      'Performance Engineering',
      'Security Hardening',
      'Application Monitoring',
      'Error Monitoring',
      'Backend Optimization',
      'Third-Party API Integration',
    ],
  },
  {
    id: 'ecommerce',
    number: '10',
    title: 'E-Commerce',
    tagline: 'Commerce Without Friction',
    headline: 'High-Converting Digital Stores',
    description:
      'Digital commerce experiences designed around discovery, trust, conversion and long-term customer relationships.',
    iconName: 'ShoppingBag',
    skills: [
      'E-Commerce Development',
      'Shopify Development',
      'WooCommerce Development',
      'Custom E-Commerce Development',
      'Headless Commerce',
      'E-Commerce Marketplace Development',
      'Product Catalog Systems',
      'Payment Gateway Integration',
      'Subscription Commerce',
      'Checkout Development',
      'Checkout Optimization',
      'E-Commerce Automation',
      'E-Commerce Analytics',
      'Product Recommendation Systems',
      'E-Commerce Search',
      'Inventory Integration',
      'Order Management Integration',
      'Customer Account Systems',
      'E-Commerce Performance Optimization',
      'E-Commerce Conversion Optimization',
    ],
  },
  {
    id: 'digital-marketing-seo',
    number: '11',
    title: 'Digital Marketing & SEO',
    tagline: 'Visibility → Demand',
    headline: 'Search & Paid Acquisition',
    description:
      'Data-informed digital marketing and search strategies designed to put businesses in front of the right people.',
    iconName: 'TrendingUp',
    skills: [
      'Digital Marketing Strategy',
      'Search Engine Optimization',
      'Technical SEO',
      'Local SEO',
      'Programmatic SEO',
      'On-Page SEO',
      'Off-Page SEO',
      'Content SEO',
      'Keyword Research',
      'Competitor SEO Analysis',
      'Search Engine Marketing',
      'Paid Advertising',
      'Google Ads Management',
      'Meta Ads Management',
      'Social Media Marketing',
      'Social Media Strategy',
      'Content Marketing',
      'Email Marketing',
      'Lead Generation',
      'Conversion Rate Optimization',
      'Marketing Analytics',
      'Marketing Funnel Development',
      'Landing Page Optimization',
      'Performance Marketing',
      'Retargeting Campaigns',
      'Search Marketing',
    ],
  },
  {
    id: 'growth-optimization',
    number: '12',
    title: 'Growth, Analytics & Continuous Dev',
    tagline: 'Scale With Intent',
    headline: 'Continuous Product Evolution',
    description:
      'We use analytics, experimentation and continuous optimization to turn launched products into growing products.',
    iconName: 'Activity',
    skills: [
      'Growth Strategy',
      'Growth Experiments',
      'Funnel Optimization',
      'Landing Page Optimization',
      'Conversion Optimization',
      'Lead Funnel Development',
      'Customer Acquisition Strategy',
      'Customer Retention Strategy',
      'Referral Systems',
      'Analytics Implementation',
      'Product Analytics',
      'Marketing Analytics',
      'A/B Testing',
      'Growth Automation',
      'Conversion Tracking',
      'Event Tracking',
      'Business Intelligence',
      'Custom Analytics Dashboards',
      'Data Visualization',
      'Marketing Attribution',
      'Website Maintenance',
      'SaaS Maintenance',
      'App Maintenance',
      'Bug Fixing',
      'Performance Optimization',
      'Core Web Vitals Optimization',
      'Security Updates',
      'Technical Audits',
      'UX Audits',
      'Conversion Audits',
      'SEO Audits',
      'Code Refactoring',
      'Infrastructure Optimization',
      'Continuous Development',
    ],
  },
];

export const TOTAL_SKILLS_COUNT = SERVICE_CATALOG.reduce(
  (acc, curr) => acc + curr.skills.length,
  0
);
